index/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
'''url for home page and about'''
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.aboutus, name='about'),
    
]

studemnt_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('school/', include('school.urls')),
    path('contactus/', include('contact.urls')),
    path('authenication/', include('authenticate_user.urls')),
    path('student/', include('student.urls')),
    path('studentmarks/', include('student_marks.urls')),
    path('studentattendance/', include('student_attendance.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="student"

urlpatterns = [
   path('', views.addstudent, name='addstudent'),
   path('viewstudent/', views.viewstudent, name='viewstudent'),
   path('editstudent/<int:student_id>/', views.editstudent, name='editstudent'),
   path('deletestudent/<int:student_id>/', views.deletestudent, name='deletestudent'),
]

student/models.py
from django.db import models




'''model for student class'''
class StudentClass(models.Model):
    student_class=models.IntegerField(blank=False)

    def __str__(self):
        return str(self.student_class)


# Create your models here.
''' model to student details'''
class StudentInfo(models.Model):
    student_id=models.CharField(max_length=10, blank=False,unique=True)
    name=models.CharField(max_length=50, blank=False)
    std_class=models.ForeignKey(StudentClass,on_delete=models.CASCADE)
    email=models.EmailField(max_length=50, blank=False)
    contact_number=models.CharField(max_length=10)
    dob=models.DateField(max_length=10, blank=False)
    father_name=models.CharField(max_length=20, blank=False)
    mother_name=models.CharField(max_length=20, blank=False)
    gender_choice =(
    ("Male", "Male"),
    ("Female", "Female"),
    ("Other", "Other"),)
    gender=models.CharField(max_length=10,choices=gender_choice)
    address=models.TextField(max_length=100, blank=False)

    def __str__(self):
        return self.name 

student/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
User=get_user_model()
from student.models import StudentInfo
# Create your forms here.


''' form to display student details '''
class NewStudentForm(forms.ModelForm):
	dob = forms.DateField(widget=forms.DateInput(attrs=dict(type='date')))

	class Meta:
		model = StudentInfo
		fields = '__all__'
		include=('dob')
		

student/views.py
from django.shortcuts import render
from .models import StudentInfo
from .forms import NewStudentForm
from django.shortcuts import  render, redirect
from django.contrib import messages
from django.template import loader
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required
def addstudent(request):
	''' Here we will add new student '''

	if request.method == "POST":
		users_form = NewStudentForm(request.POST)
		if users_form.is_valid():
			users_form.save()
			messages.success(request, "Added student successful." )
			return redirect('/student')
		else:
			print(users_form.errors)
		messages.error(request,users_form.errors,"Invalid ") 
	users_form=NewStudentForm()
	return render(request,'student/addstudent.html',context={"add":users_form})

@login_required
def viewstudent(request):
	'''here we will view all the student details'''

	studentdata = StudentInfo.objects.all().order_by("std_class")
	template = loader.get_template('student/studentDetails.html')
	context={'studentdata':studentdata}
	return HttpResponse(template.render(context, request))

@login_required
def editstudent(request,student_id):
	'''Here we will edit the particular student through student_id'''

	student_data=StudentInfo.objects.get(pk=student_id)
	form=NewStudentForm(instance=student_data)
	if request.method == "POST":
		form = NewStudentForm(request.POST ,instance=student_data)
		if form.is_valid():
			form.save(commit=True)
			messages.success(request, "updated successfully." )
			return viewstudent(request)
		else:
			print(form.errors)
		messages.error(request,form.errors,"Invalid ") 
	diction={'edit_student':form}
	return render(request,'student/editstudent.html',context=diction)

@login_required
def deletestudent(request,student_id):
	'''Here we will delete the particular student details through student_id'''
	student=StudentInfo.objects.get(pk=student_id)
	student.delete()
	messages.success(request, "Deleted successfully." )
	return redirect('/student/viewstudent')
	

templates/student/addstudent.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block title %}
Student Details    
{% endblock %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<!-- <div class="text-center"><button class="btn btn-success" type="submit">ADD new student</button></div> -->
<div class="justify-content-center" style="margin-top: 96px;display: flex; align-items: center; margin-top: 52px;
">

    <form action="" method="POST" style="width: 400px; align-items: center;">
      <h2>Register New Student</h2><br>
      {% csrf_token %}
      {{ add|crispy }}                    
    <button class="btn btn-primary" type="submit">Add student</button>
    </form>
  </div>


{% endblock %}



       

templates/student/editstudent.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block title %}
Student Details    
{% endblock %}

{% block content %}


<!-- <div class="text-center"><button class="btn btn-success" type="submit">ADD new student</button></div> -->
<div class="justify-content-center" style="margin-top: 96px;display: flex; align-items: center; margin-top: 52px;
">

    <form action="" method="POST" style="width: 400px; align-items: center;">
      <h2>Edit student</h2><br>
      {% csrf_token %}
      {{ edit_student.as_p}}                    
    <button class="btn btn-primary" type="submit">Update</button>
    </form>
  </div>


{% endblock %}



       

templates/student/studentDetails.html
{% extends 'layout.html' %}


{% block style %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 80%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}


</style>
  {% endblock %}
{% block title %}
Student Details    
{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<table>
    <tr>
      <th>Student ID</th>
      <th>Name</th>
      <th>Student class</th>
      <th>Email</th>
      <th>Contact number</th>
      <th>DOB</th>
      <th>Father name</th>
      <th>Mother name</th>
      <th>Gender</th>
      <th>Address</th>
    </tr>
    {% for field in studentdata %}
      <tr>
        <td>{{ field.student_id }}</td>
        <td>{{ field.name }}</td>
        <td>{{ field.std_class}}</td>
        <td>{{ field.email }}</td>
        <td>{{ field.contact_number }}</td>
        <td>{{ field.dob }}</td>
        <td>{{ field.father_name }}</td>
        <td>{{ field.mother_name }}</td>
        <td>{{ field.gender }}</td>
        <td>{{ field.address }}</td>
        <td><a href="{% url 'student:editstudent' student_id=field.id %}" class="btn btn-primary">EDIT</a><p style="display:none;">{{ field.id}}</p></td>
        <td><a href="{% url 'student:deletestudent' student_id=field.id %}" class="btn btn-danger" onclick="return confirm('Do you want to delete?')">DELETE</a></td>
      </tr>
    {% endfor %}
  </table>


{% endblock %}



       