index/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
'''url for home page and about'''
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.aboutus, name='about'),
    
]

studemnt_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('school/', include('school.urls')),
    path('contactus/', include('contact.urls')),
    path('authenication/', include('authenticate_user.urls')),
    path('student/', include('student.urls')),
    path('studentmarks/', include('student_marks.urls')),
    path('studentattendance/', include('student_attendance.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student_attendance/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="attendance"
urlpatterns = [
   path('', views.addAttendance, name='addAttendance'),
   path('viewattendance', views.viewattendance, name='viewattendance'),
   path('editattendance/<int:student_id>/', views.editattendance, name='editattendance'),
   path('deleteattendance/<int:student_id>/', views.deleteattendance, name='deleteattendance'),
   path('load_names', views.load_names, name='load_names'),
   
]

student_attendance/models.py
from django.db import models
from student.models import StudentClass,StudentInfo
# Create your models here.

    
'''model for attendance details'''
class StudentAttendance(models.Model):
    student_class=models.ForeignKey(StudentClass,on_delete=models.CASCADE)
    student_name=models.ForeignKey(StudentInfo, on_delete=models.CASCADE)
    attendance_choice=(("Present","Present"),("Absent","Absent"))
    attendance=models.CharField(max_length=10,choices=attendance_choice)
    date=models.DateField()

    def __str__(self):
        return str(self.student_name)

student_attendance/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from student.models import StudentClass,StudentInfo
User=get_user_model()
from .models import StudentAttendance

# Create your forms here.

class AllStudentAttendance(forms.ModelForm):
    attendance_choice=(("Present","Present"),("Absent","Absent"))
    date=forms.DateField(widget=forms.DateInput(attrs=dict(type='date')))
    attendance= forms.CharField(widget=forms.RadioSelect(choices=attendance_choice))
    class Meta:
        model=StudentAttendance
        fields = '__all__'
        include=('date','attendance')
        
        
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['name'].queryset = StudentInfo.objects.none()

           
            if 'student_class' in self.data:
                try:
                    class_id = int(self.data.get('student_class'))
                    self.fields['student_name'].queryset = StudentInfo.objects.filter(std_class=class_id).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
            

student_attendance/views.py
from django.shortcuts import render
from django.shortcuts import  render, redirect
from .forms import AllStudentAttendance
from .models import StudentAttendance
from student.models import StudentInfo,StudentClass
from django.template import loader
from django.http import HttpResponse
from django.contrib import messages
from django.http import JsonResponse
import json
from django.db.models import Count
from django.contrib.auth.decorators import login_required

@login_required
def addAttendance(request):
	'''Here we add addtendance to student '''
	attendance_details=AllStudentAttendance()
    
	if request.method == "POST":
		attendance_details=AllStudentAttendance(request.POST)
		student_name = request.POST.get('student_name')
		print(student_name)
		date = request.POST.get('date')
		data_exist= StudentAttendance.objects.filter(student_name=student_name ,date=date).exists()
		print(data_exist)
		if not(data_exist):
			if attendance_details.is_valid():
				attendance_details.save()
				return redirect('/studentattendance/viewattendance')
			else:
				print(attendance_details.errors)
		else:
			messages.error(request,"Data Already Exist")
			
	return render(request,'student_attendance/add_attendance.html',context={"attendance_details":attendance_details})

@login_required
def viewattendance(request):
	'''display all attendance of student'''

	attendancedata = StudentAttendance.objects.all().order_by('student_class','date')
	
	count_attendance=StudentAttendance.objects.values('attendance').order_by().annotate(Count('attendance'))
	print(count_attendance)
	total_present=count_attendance[1]['attendance__count']                    #to count present
	template = loader.get_template('student_attendance/display_attendance.html')
	context={'attendancedata':attendancedata,'total_present':total_present}
	return HttpResponse(template.render(context, request))

@login_required
def editattendance(request,student_id):
	'''Here we edit the attendance and update '''

	attendance_data=StudentAttendance.objects.get(pk=student_id)
	form=AllStudentAttendance(instance=attendance_data)
	if request.method == "POST":
		form = AllStudentAttendance(request.POST ,instance=attendance_data)
		if form.is_valid():
			form.save(commit=True)
			messages.success(request, "updated successfully." )
			return viewattendance(request)
		else:
			print(form.errors)
		messages.error(request,form.errors,"Invalid ") 
	diction={'edit_attendance':form}
	return render(request,'student_attendance/edit_attendance.html',context=diction)


@login_required
def deleteattendance(request,student_id):
	'''Here we delete the marks'''

	attendance=StudentAttendance.objects.get(pk=student_id)
	print(attendance)
	attendance.delete()
	messages.success(request, "Deleted successfully." )
	return redirect('/studentattendance/viewattendance')


@login_required
def load_names(request):
    # attendance_details=AllStudentAttendance(request.POST)
    data = json.loads(request.body)
    cls=data['id']
    name = StudentInfo.objects.filter(std_class=cls)
    return JsonResponse(list(name.values("id","name")), safe=False)
    

templates/student_attendance/add_attendance.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block style %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 80%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}


</style>


  {% endblock %}
{% block title %}
Student Details    
{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<div class="justify-content-center" style="margin-top: 96px;display: flex; align-items: center; margin-top: 52px;
">

    <form action="" method="POST" id="attendanceForm" data-url={% url 'attendance:addAttendance'%} style="width: 400px; align-items: center;">
      
      <h2>Attendance Details</h2><br>
      {% csrf_token %}
      {{ attendance_details|crispy }} 
    <button class="btn btn-primary" type="submit">ADD  ATTENDANCE</button>
    </form>
  </div>


  <script>

    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }
    const csrftoken = getCookie('csrftoken');


    let std_class_field = document.getElementById("id_student_class")
    let name_field = document.getElementById("id_student_name")
    
    std_class_field.addEventListener("change", getname)
    function getname(e){
        class_id = e.target.value
        console.log(class_id)
        const data = { id: class_id}
        let url = " {% url 'attendance:load_names' %} "

fetch(url, {
method: 'POST',
headers: {
'Content-Type': 'application/json',
'X-CSRFToken': csrftoken
},
body: JSON.stringify(data),
})
.then(response => response.json())
.then(data => {
console.log('Success:', data[0]['name']);

name_field.innerHTML = `<option value = "" selected>--------------</option>`
/*for(let i = 0; i<data.length; i++){
  name_field.innerHTML += `<option value = `+data[i]["id"]+`>`+data[i]["name"]+`</option>`

}*/
data.forEach(function(item,index){
  name_field.innerHTML += `<option value = `+item["id"]+`>`+item["name"]+`</option>`
})
})
.catch((error) => {
console.error('Error:', error);
});

    }

    let input = document.getElementById("id_name")
    let select = document.getElementsByTagName("select")
    console.log(select)

    input.classList.add("form-control")

    for(let i = 0; i <select.length; i++){
        select[i].classList.add("form-select")
    }
</script>

{% endblock %}



       

templates/student_attendance/display_attendance.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block style %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 80%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
h2 {
  text-align: center;
}


</style>


  {% endblock %}
{% block title %}
Student Details    
{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<h2>Student Attendance Details</h2><br>

  <table>
    <tr>
      <th>Student class</th>
      <th>Name</th>
      <th>Date</th>
      <th>Attendance</th>
    </tr>
    {% for field in attendancedata %}
      <tr>
        
        <td>{{ field.student_class }}</td>
        <td>{{ field.student_name }}</td>
        <td>{{ field.attendance }}</td>
        <td>{{ field.date }}</td>
        <td><a href="{% url 'attendance:editattendance' student_id=field.id %}" class="btn btn-primary">EDIT</a><p style="display:none;">{{ field.id}}</p></td>
        <td><a href="{% url 'attendance:deleteattendance' student_id=field.id %}" class="btn btn-danger" onclick="return confirm('Do you want to delete?')">DELETE</a></td>
       
        
      </tr> 
    {% endfor %}
    
  </table>
  
  

{% endblock %}



       

templates/student_attendance/edit_attendance.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block title %}
Student Details    
{% endblock %}

{% block content %}


<!-- <div class="text-center"><button class="btn btn-success" type="submit">ADD new student</button></div> -->
<div class="justify-content-center" style="margin-top: 96px;display: flex; align-items: center; margin-top: 52px;
">

    <form action="" method="POST" style="width: 400px; align-items: center;">
      <h2>Edit Attendance</h2><br>
      {% csrf_token %}
      {{ edit_attendance.as_p}}                    
    <button class="btn btn-primary" type="submit">Update</button>
    </form>
  </div>


{% endblock %}



       