contact/urls.py
from django.contrib import admin
from django.urls import path
from contact import views



urlpatterns = [
   
    path('', views.contactus, name='contact'),

]

index/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
'''url for home page and about'''
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.aboutus, name='about'),
    
]

studemnt_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('school/', include('school.urls')),
    path('contactus/', include('contact.urls')),
    path('authenication/', include('authenticate_user.urls')),
    path('student/', include('student.urls')),
    path('studentmarks/', include('student_marks.urls')),
    path('studentattendance/', include('student_attendance.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="student"

urlpatterns = [
   path('', views.addstudent, name='addstudent'),
   path('viewstudent/', views.viewstudent, name='viewstudent'),
   path('editstudent/<int:student_id>/', views.editstudent, name='editstudent'),
   path('deletestudent/<int:student_id>/', views.deletestudent, name='deletestudent'),
]

student_attendance/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="attendance"
urlpatterns = [
   path('', views.addAttendance, name='addAttendance'),
   path('viewattendance', views.viewattendance, name='viewattendance'),
   path('editattendance/<int:student_id>/', views.editattendance, name='editattendance'),
   path('deleteattendance/<int:student_id>/', views.deleteattendance, name='deleteattendance'),
   path('load_names', views.load_names, name='load_names'),
   
]

student_marks/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="marks"
urlpatterns = [
   path('', views.addMarks, name='addmarks'),
   path('viewmarks/', views.viewmarks, name='viewmarks'),
   path('editmarks/<int:student_id>/', views.editmarks, name='editmarks'),
   path('deletemarks/<int:student_id>/', views.deletemarks, name='deletemarks'),
]

contact/models.py
from django.db import models

# Create your models here.
'''model to display the contact detail of school'''
class contactlist(models.Model):
    address=models.TextField(max_length=900, blank=False)
    email=models.CharField(max_length=100, blank=False)
    phone=models.CharField(max_length=100, blank=False)

    def __str__(self):
        return self.email

'''model to get the inquery form details'''
class contactform(models.Model):
    name=models.CharField(max_length=100, blank=False)
    email=models.CharField(max_length=100, blank=False)
    subject=models.CharField(max_length=100, blank=False)
    message=models.TextField(max_length=800, blank=False)

    def __str__(self):
        return self.name

contact/views.py
from django.shortcuts import render
from .models import contactlist
from .models import contactform
from django.core.mail import send_mail
# Create your views here.
def contactus(request):
    '''to show contact infromation and to take the query'''
    if request.method== 'POST':
        name=request.POST.get('name')
        email=request.POST.get('email')
        subject=request.POST.get('subject')
        message=request.POST.get('message')

        contactformdata=contactform(name=name,email=email,subject=subject,message=message)
        contactformdata.save()
        a=(contactform).objects.all()
        print(a)

        send_mail(
    f'{subject}',
    f'{message}',
    f'{email}',
    ['info@laps.com'],
    fail_silently=False,
)
        
    contactlistdata=contactlist.objects.all()
    context={
        'contactlist':contactlistdata,
        
    }
    return render(request,'contact.html',context)

templates/about.html
{% extends 'layout.html' %}

{% block title %}
   about     
{% endblock %}

{% block content %}
{% load static %}
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>About Us</h2>
        <ol>
          <li><a href="{% url 'home'%}">Home</a></li>
          <li>About Us </li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs -->
 <!-- ======= About Us Section ======= -->
 <section id="about-us" class="about-us">
    <div class="container" data-aos="fade-up">

      <div class="section-title">
        <br><br>
        <h2>About Us</strong></h2>
      </div>
      {% for abt in about %}
      <div class="row content">
        <div class="col-lg-6" data-aos="fade-right">
          <h2>{{ abt.title}}</h2>
          <img src="{{ abt.Image.url }}" alt="" style="height: 200px; width: 400px;">
        </div>
        <div class="col-lg-6 pt-4 pt-lg-0" data-aos="fade-left">
          <p>
              {{ abt.description }}
          </p>
        </div>
        {% endfor %}
      </div>

    </div>
  </section><!-- End About Us Section -->
{% endblock %}

templates/contact.html
{% extends 'layout.html' %}


{% block title %}
   contact     
{% endblock %}
{% block content %}
 <!-- ======= Breadcrumbs ======= -->
 <section id="breadcrumbs" class="breadcrumbs">
    <div class="container">

      <div class="d-flex justify-content-between align-items-center">
        <h2>Contact</h2>
        <ol>
          <li><a href="{% url 'home'%}">Home</a></li>
          <li>Contact</li>
        </ol>
      </div>

    </div>
  </section><!-- End Breadcrumbs -->

  <!-- ======= Contact Section ======= -->
  

  <section id="contact" class="contact">
    <div class="container">

      <div class="row justify-content-center" data-aos="fade-up">
        {% for row in contactlist %}
        <div class="col-lg-10">

          <div class="info-wrap">
            <div class="row">
              <div class="col-lg-4 info">
                <i class="bi bi-map"></i>
                <h4>Location:</h4>
                <p>{{ row.address }}</p>
              </div>

              <div class="col-lg-4 info mt-4 mt-lg-0">
                <i class="bi bi-envelope"></i>
                <h4>Email:</h4>
                <p>{{ row.email }}</p>
              </div>

              <div class="col-lg-4 info mt-4 mt-lg-0">
                <i class="bi bi-telephone"></i>
                <h4>Call:</h4>
                <p>{{ row.phone }}</p>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>

      </div>

      <div class="row mt-5 justify-content-center" data-aos="fade-up">
        <div class="col-lg-10">
          <form action="" method="post">
            {% csrf_token%}
            <div class="form-row">
              <div class="col-md-6 form-group">
                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name"  />
                <div class="validate"></div>
              </div>
              <div class="col-md-6 form-group">
                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" />
                <div class="validate"></div>
              </div>
            </div>
            <div class="form-group">
              <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" />
              <div class="validate"></div>
            </div>
            <div class="form-group">
              <textarea class="form-control" placeholder="message"  name="message" rows="5" ></textarea>
              <div class="validate"></div>
            </div>
            
            <div class="text-center"><button class="btn btn-success" type="submit">Send Message</button></div>
          </form>
        </div>

      </div>

    </div>
  </section><!-- End Contact Section -->
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block title %}
   home     
{% endblock %}
{% block content %}
{% include 'slider.html' with sliderdata=slider %}
{% load static %}

  <marquee  direction="left" height="100px" style="background-color: darkgrey;
  height: 60px;
  padding-top: 19px;">
  {% for m in notice %}{{ m.message }}{% endfor %}
  </marquee>

  <br>
  <h2 class="text-center">WELCOME TO LITTLE ANGELS</h2>
 <div class="jumbotron">
  <p>The first biggest dream of Prahallad Gahir turned into a vibrant reality when Little Angels Public School, Barpali was formally inaugurated in 2010. 
  
  The school, affiliated to Central Board of Secondary Education (CBSE) has been able to provide a perfect blend of academics, sports, and co-curricular activities for all the students from Grades Nursery-XII since its inception.</p></div>

  <img src="{% static 'image/schoolhome.jpeg' %}" class="img-fluid" alt="">

  <!-- Remove the container if you want to extend the Footer to full width. -->
<div class=" my-5">
  <!-- Footer -->
  <footer
          class="text-center text-lg-start text-white"
          style="background-color: #45526e"
          >
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">
              Angels Academy
            </h6>
            <p>
              Education To All........
            </p>
          </div>
          <!-- Grid column -->

          <hr class="w-100 clearfix d-md-none" />

          

          <hr class="w-100 clearfix d-md-none" />

          
          <hr class="w-100 clearfix d-md-none" />

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
            <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
            <p><i class="fas fa-home mr-3"></i> Main road ,Barpali,Bargarh ,Odisha pin -768029</p>
            <p><i class="fas fa-envelope mr-3"></i> info@laps.com</p>
            <p><i class="fas fa-phone mr-3"></i> 8456538752</p>
          </div>
          <!-- Grid column -->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->

      <hr class="my-3">

      
    </div>
    <!-- Grid container -->
  </footer>
  <!-- Footer -->
</div>
<!-- End of .container -->
{% endblock %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  {% block style %}

  {% endblock %}
  <title>{% block title %}

    {% endblock %}</title>
  <meta content="" name="descriptison">
  <meta content="" name="keywords">

  

  
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Roboto:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
  <link rel=”stylesheet” href=”https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css”/>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="jquery-3.6.3.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>

  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function()
  {
      var $select1=$('#id_Class'),
          $select2=$('#id_name'),    
          $options=$select2.find('option');
          $select1.on('change',function()
          {
              $select2.html($options.filter('[value="'+this.value+'"]'));
          }).trigger('change');
  });
</script> -->

  
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo mr-auto"><span>Angels </span>Academy</h1>
     

      <nav class="nav-menu d-none d-lg-block">
        <ul>
          <li class="active"><a href="{% url 'home'%}">Home</a></li>
          <li><a href="{% url 'about'%}">About</a></li>
          <li><a href="{% url 'contact'%}">Contact</a></li>
          {% if user.is_authenticated %}
          <li class="drop-down"><a href="#">Student</a>
            <ul>
              <li><a href="{% url 'student:addstudent' %}">Add Student</a></li>
              <li><a href="{% url 'student:viewstudent' %}">View student Details</a></li>
              <li><a href="{% url 'attendance:addAttendance' %}">Add Attendance</a></li>
              <li><a href="{% url 'attendance:viewattendance' %}">View Attendance</a></li>

            </ul>
          </li>
          <li class="drop-down"><a href="#">Marks</a>
            <ul>
              <li><a href="{% url 'marks:addmarks' %}">Add Marks</a></li>
              <li><a href="{% url 'marks:viewmarks' %}">View Marks</a></li>
            </ul>
          </li>
          
          
          <li><a href="{% url 'profile'%}">My Profile</a></li>
          {% else %}
          <li><a href="{% url 'login'%}">My Account</a></li>
          {% endif %}

        </ul>
      </nav><!-- .nav-menu -->
    </div>
  </header><!-- End Header -->

  <main id="main" style="margin-top: 78px;
">
    {% block content %}

    {% endblock %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->

  <a href="#" class="back-to-top"><i class="icofont-simple-up"></i></a>

 

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
 
</body>

</html>

templates/slider.html
{% load static %}


<!-- ======= Hero Section ======= -->
<section id="hero">
    <div id="heroCarousel" class="carousel slide carousel-fade" data-ride="carousel">

      <div class="carousel-inner" role="listbox">

        {% for row in sliderdata %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}" style="background-image: url({{row.Image.url}});">
            <div class="carousel-container">
                <div class="carousel-content animate__animated animate__fadeInUp">
                <h2>{{ row.title }}</h2>
                <p>{{ row.description }}</p>
                </div>
            </div>
            </div>
        {% endfor %}
        

      </div>

      <a class="carousel-control-prev" href="#heroCarousel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon icofont-simple-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>

      <a class="carousel-control-next" href="#heroCarousel" role="button" data-slide="next">
        <span class="carousel-control-next-icon icofont-simple-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

      <ol class="carousel-indicators" id="hero-carousel-indicators"></ol>

    </div>
  </section><!-- End Hero -->