index/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
'''url for home page and about'''
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.aboutus, name='about'),
    
]

studemnt_management_system/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('index.urls')),
    path('school/', include('school.urls')),
    path('contactus/', include('contact.urls')),
    path('authenication/', include('authenticate_user.urls')),
    path('student/', include('student.urls')),
    path('studentmarks/', include('student_marks.urls')),
    path('studentattendance/', include('student_attendance.urls')),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student_marks/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="marks"
urlpatterns = [
   path('', views.addMarks, name='addmarks'),
   path('viewmarks/', views.viewmarks, name='viewmarks'),
   path('editmarks/<int:student_id>/', views.editmarks, name='editmarks'),
   path('deletemarks/<int:student_id>/', views.deletemarks, name='deletemarks'),
]

templates/marks/addmarks.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block title %}
Student Details    
{% endblock %}

{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<!-- <div class="text-center"><button class="btn btn-success" type="submit">ADD new student</button></div> -->
<div class="justify-content-center" style="margin-top: 96px;display: flex; align-items: center; margin-top: 52px;
">

    <form action="" method="POST" style="width: 400px; align-items: center;">
      <h2>Enter Marks Details</h2><br>
      {% csrf_token %}
      {{ addmarks|crispy }}                    
    <button class="btn btn-primary" type="submit">Add Marks</button>
    </form>
  </div>


{% endblock %}



       

templates/marks/edit_marks.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}

{% block title %}
edit marks    
{% endblock %}

{% block content %}


<!-- <div class="text-center"><button class="btn btn-success" type="submit">ADD new student</button></div> -->
<div class="justify-content-center" style="margin-top: 96px;display: flex; align-items: center; margin-top: 52px;
">

    <form action="" method="POST" style="width: 400px; align-items: center;">
      <h2>Edit student</h2><br>
      {% csrf_token %}
      {{ edit_marks.as_p}}                    
    <button class="btn btn-primary" type="submit">Update</button>
    </form>
  </div>


{% endblock %}



       

templates/marks/viewmarks.html
{% extends 'layout.html' %}


{% block style %}
<style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 80%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

.heading {
    align-items: center;
}

</style>
  {% endblock %}
{% block title %}
Student Details    
{% endblock %}

{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<h2 class="heading">Student Marks </h2>
<table>
    <tr>
      <th>student Name</th>
      <th>Hindi</th>
      <th>English</th>
      <th>Math</th>
      <th>Science</th>
      <th>SST</th>
      <th>Total</th>
      <th>Percentage</th>
    </tr>
    {% for field in marksdata %}
      <tr>
        <td>{{ field.student_name }}</td>
        <td>{{ field.hindi }}</td>
        <td>{{ field.english}}</td>
        <td>{{ field.math }}</td>
        <td>{{ field.science }}</td>
        <td>{{ field.sst }}</td>
        <td>{{ field.total }}</td>
        <td>{{ field.percentage }}</td>
        <td><a href="{% url 'marks:editmarks' student_id=field.id %}" class="btn btn-primary">EDIT</a></td>
        <td><a href="{% url 'marks:deletemarks' student_id=field.id %}" class="btn btn-danger" onclick="return confirm('Do you want to delete?')">DELETE</a></td>
        
      </tr>
    {% endfor %}
  </table>


{% endblock %}



       